### ISSUE TITLE
微博接口跨域

### ISSUE THREAD

**Issue by Dandy-97** [hehehai/weibo-worth#1]
您好，请问该项目中的微博接口请求跨域问题是如何解决的，谢谢。
![Snipaste_2024-05-23_15-56-29](https://github.com/hehehai/weibo-worth/assets/107861593/5f7b71b8-e8e3-4868-b3cb-84c3dfe43049)

**Comment by hehehai** [comment]
@Dandy-97 浏览器是无法避免的，需要把请求放在服务端实现
